<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5RB1QFG" name="TestCases.HomePageTestCases" tests="19" failures="0" timestamp="16 Aug 2017 17:03:21 GMT" time="123.255" errors="2">
  <testcase name="testCase106" time="6.296" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase097" time="5.537" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase100" time="5.717" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase110" time="6.996" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase096" time="6.327" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase104" time="5.851" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase109" time="7.411" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase099" time="5.866" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase107" time="6.228" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase098" time="5.461" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase094" time="7.079" classname="TestCases.HomePageTestCases">
    <error type="java.lang.AssertionError" message="Test FAILED">
      <![CDATA[java.lang.AssertionError: Test FAILED
	at org.testng.Assert.fail(Assert.java:94)
	at TestCases.HomePageTestCases.testCase094(HomePageTestCases.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </error>
  </testcase> <!-- testCase094 -->
  <testcase name="testCase103" time="5.732" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase105" time="6.267" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase095" time="8.525" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase102" time="5.561" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase090" time="7.431" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase108" time="8.256" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase101" time="5.676" classname="TestCases.HomePageTestCases"/>
  <testcase name="testCase092" time="7.038" classname="TestCases.HomePageTestCases">
    <error type="java.lang.AssertionError" message="Test FAILED">
      <![CDATA[java.lang.AssertionError: Test FAILED
	at org.testng.Assert.fail(Assert.java:94)
	at TestCases.HomePageTestCases.testCase092(HomePageTestCases.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </error>
  </testcase> <!-- testCase092 -->
</testsuite> <!-- TestCases.HomePageTestCases -->
