<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5RB1QFG" name="TestCases.ProtocolTestCases" tests="61" failures="0" timestamp="16 Aug 2017 17:03:21 GMT" time="637.310" errors="2">
  <testcase name="testCase026" time="7.701" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase040" time="9.536" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase032" time="8.788" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase052" time="44.564" classname="TestCases.ProtocolTestCases">
    <error type="java.lang.AssertionError" message="Test FAILED">
      <![CDATA[java.lang.AssertionError: Test FAILED
	at org.testng.Assert.fail(Assert.java:94)
	at TestCases.ProtocolTestCases.testCase052(ProtocolTestCases.java:1060)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </error>
  </testcase> <!-- testCase052 -->
  <testcase name="testCase020" time="9.038" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase036" time="8.875" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase043" time="8.610" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase075" time="8.422" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase044" time="9.821" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase069" time="8.859" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase054" time="11.335" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase071" time="8.920" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase073" time="8.720" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase077" time="10.448" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase027" time="8.540" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase056" time="8.094" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase035" time="9.631" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase030" time="8.518" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase022" time="8.173" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase061" time="8.556" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase065" time="8.500" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase038" time="9.330" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase048" time="9.064" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase076" time="9.131" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase074" time="8.610" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase060" time="7.844" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase025" time="10.798" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase041" time="8.547" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase062" time="8.968" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase063" time="8.405" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase019" time="9.511" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase024" time="9.329" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase078" time="10.471" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase045" time="9.515" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase050" time="8.400" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase021" time="8.368" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase037" time="8.762" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase059" time="8.713" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase051" time="9.298" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase068" time="8.181" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase072" time="8.844" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase058" time="9.351" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase079" time="43.656" classname="TestCases.ProtocolTestCases">
    <error type="java.lang.AssertionError" message="Test FAILED">
      <![CDATA[java.lang.AssertionError: Test FAILED
	at org.testng.Assert.fail(Assert.java:94)
	at TestCases.ProtocolTestCases.testCase079(ProtocolTestCases.java:1882)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </error>
  </testcase> <!-- testCase079 -->
  <testcase name="testCase023" time="9.388" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase047" time="9.283" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase046" time="9.657" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase034" time="8.411" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase033" time="8.623" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase067" time="8.410" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase053" time="11.917" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase028" time="9.676" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase049" time="10.585" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase070" time="8.603" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase039" time="9.325" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase055" time="9.250" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase057" time="8.804" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase066" time="8.493" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase064" time="8.965" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase029" time="8.491" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase031" time="22.840" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase042" time="9.844" classname="TestCases.ProtocolTestCases"/>
</testsuite> <!-- TestCases.ProtocolTestCases -->
