<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5RB1QFG" name="TestCases.ProtocolTestCases" tests="61" failures="0" timestamp="15 Aug 2017 16:47:44 GMT" time="608.354" errors="2">
  <testcase name="testCase024" time="7.656" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase064" time="9.775" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase062" time="8.664" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase033" time="8.179" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase026" time="7.692" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase021" time="7.564" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase073" time="8.243" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase041" time="8.349" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase067" time="8.621" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase027" time="8.592" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase028" time="8.387" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase046" time="8.344" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase076" time="8.749" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase069" time="8.607" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase022" time="7.635" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase042" time="8.260" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase036" time="8.116" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase063" time="9.562" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase060" time="8.158" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase019" time="8.741" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase034" time="8.098" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase040" time="8.771" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase052" time="44.115" classname="TestCases.ProtocolTestCases">
    <error type="java.lang.AssertionError" message="Test FAILED">
      <![CDATA[java.lang.AssertionError: Test FAILED
	at org.testng.Assert.fail(Assert.java:94)
	at TestCases.ProtocolTestCases.testCase052(ProtocolTestCases.java:1060)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </error>
  </testcase> <!-- testCase052 -->
  <testcase name="testCase071" time="8.277" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase029" time="8.713" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase037" time="8.718" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase058" time="8.356" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase049" time="9.359" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase075" time="8.069" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase038" time="9.520" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase070" time="8.361" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase056" time="7.857" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase039" time="8.635" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase025" time="8.190" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase051" time="8.113" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase059" time="9.133" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase035" time="8.093" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase078" time="10.616" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase020" time="8.134" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase044" time="8.572" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase050" time="8.218" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase065" time="7.970" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase023" time="8.924" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase077" time="9.771" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase061" time="7.980" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase031" time="22.919" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase066" time="8.200" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase045" time="8.195" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase055" time="7.463" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase032" time="9.138" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase068" time="8.279" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase072" time="8.811" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase054" time="11.087" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase047" time="8.450" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase030" time="8.700" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase074" time="9.114" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase043" time="8.120" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase079" time="44.214" classname="TestCases.ProtocolTestCases">
    <error type="java.lang.AssertionError" message="Test FAILED">
      <![CDATA[java.lang.AssertionError: Test FAILED
	at org.testng.Assert.fail(Assert.java:94)
	at TestCases.ProtocolTestCases.testCase079(ProtocolTestCases.java:1882)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </error>
  </testcase> <!-- testCase079 -->
  <testcase name="testCase053" time="10.398" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase048" time="8.911" classname="TestCases.ProtocolTestCases"/>
  <testcase name="testCase057" time="7.898" classname="TestCases.ProtocolTestCases"/>
</testsuite> <!-- TestCases.ProtocolTestCases -->
